// Regenerates TypeScript types from the committed contracts. Run after changing anything in /contracts.
import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";
import openapiTS, { astToString } from "openapi-typescript";

const root = join(dirname(fileURLToPath(import.meta.url)), "../../..");
const out = join(root, "packages/contracts/src/generated");
const banner = "/* Generated by packages/contracts/scripts/generate.mjs. Do not edit. */\n";

const api = await openapiTS(new URL(`file://${join(root, "contracts/openapi/replen-api.v1.yaml")}`));
await writeFile(join(out, "api.ts"), banner + astToString(api));

const opts = { bannerComment: "", additionalProperties: false, unreachableDefinitions: true, style: { singleQuote: false } };
for (const [file, name] of [
  ["contracts/engine/plan-request.v1.schema.json", "PlanRequest"],
  ["contracts/engine/plan-response.v1.schema.json", "PlanResponse"],
]) {
  const schema = JSON.parse(await readFile(join(root, file), "utf8"));
  const ts = await compile(schema, name, opts);
  await writeFile(join(out, `engine-${name === "PlanRequest" ? "request" : "response"}.ts`), banner + ts);
}

const index = JSON.parse(await readFile(join(root, "contracts/events/index.json"), "utf8"));
let events = banner;
const names = [];
for (const [type, file] of Object.entries(index.events)) {
  const schema = JSON.parse(await readFile(join(root, "contracts/events", file), "utf8"));
  const typeName = type
    .replace(/^replen\./, "")
    .replace(/\.v(\d+)$/, "V$1")
    .split(/[.-]/)
    .map((p) => p[0].toUpperCase() + p.slice(1))
    .join("");
  names.push([type, typeName]);
  delete schema.$id;
  events += await compile({ ...schema, title: typeName }, typeName, opts);
}
events += "\nexport interface EventDataByType {\n" + names.map(([t, n]) => `  "${t}": ${n};\n`).join("") + "}\n";
events += "\nexport type EventType = keyof EventDataByType;\n";
await writeFile(join(out, "events.ts"), events);
console.log("generated", ["api.ts", "engine-request.ts", "engine-response.ts", "events.ts"].join(", "));
