"""HTTP interface for on-demand planning and what-if simulation."""

from __future__ import annotations

import json
import logging
import os
import sys
import threading
import time
import uuid
from pathlib import Path

from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import JSONResponse

from . import __version__
from .contracts import CONTRACT_VERSION, PlanRequest, PlanResponse
from .planner import plan
from .store import AnalyticsStore

logger = logging.getLogger("replen.engine")
if not logger.handlers:
    handler = logging.StreamHandler(sys.stdout)
    handler.setFormatter(logging.Formatter("%(message)s"))
    logger.addHandler(handler)
    logger.setLevel(logging.INFO)


def _log(**fields) -> None:
    logger.info(json.dumps({"service": "replen-engine", **fields}, default=str))


REFERENCE_FILES = [
    "locations.csv",
    "suppliers.csv",
    "products.csv",
    "sourcing.csv",
    "item_locations.csv",
    "order_constraints.csv",
    "inventory_snapshot.csv",
    "open_purchase_orders.csv",
    "po_receipt_history.csv",
]


class SyntheticBootstrap:
    """Serverless mode: generate the deterministic dataset and load the store on first use in each instance.

    Enabled by ENGINE_BOOTSTRAP=1. The dataset is regenerated byte-for-byte from the seed, so every instance
    serves identical history without shipping data files.
    """

    def __init__(self, store: AnalyticsStore, directory: Path, enabled: bool):
        self.store = store
        self.directory = directory
        self.enabled = enabled
        self._lock = threading.Lock()
        self._ready = False

    def ensure(self) -> None:
        if not self.enabled or self._ready:
            return
        with self._lock:
            if self._ready:
                return
            t = time.perf_counter()
            if not (self.directory / "manifest.json").exists():
                from .synthetic import generate

                generate(self.directory)
            if self.store.status()["salesRows"] == 0:
                self.store.import_dir(self.directory)
            self._ready = True
            _log(msg="synthetic bootstrap complete", seconds=round(time.perf_counter() - t, 2))


def create_app(store: AnalyticsStore | None = None) -> FastAPI:
    store = store or AnalyticsStore(os.environ.get("ENGINE_DUCKDB_PATH", ".data/analytics.duckdb"))
    synthetic_dir = os.environ.get("ENGINE_SYNTHETIC_DIR")
    bootstrap = SyntheticBootstrap(
        store, Path(synthetic_dir or "/tmp/replen-synthetic"), os.environ.get("ENGINE_BOOTSTRAP") == "1"
    )
    app = FastAPI(title="replen-engine", version=__version__)

    @app.middleware("http")
    async def correlation(request: Request, call_next):
        cid = request.headers.get("x-correlation-id") or str(uuid.uuid4())
        t = time.perf_counter()
        response = await call_next(request)
        response.headers["x-correlation-id"] = cid
        _log(
            msg="request",
            method=request.method,
            path=request.url.path,
            status=response.status_code,
            durationMs=round((time.perf_counter() - t) * 1000, 1),
            correlationId=cid,
        )
        return response

    @app.get("/health")
    def health():
        return {
            "status": "ok",
            "engineVersion": __version__,
            "contractVersion": CONTRACT_VERSION,
            "store": store.status(),
        }

    @app.post("/v1/plans", response_model=PlanResponse, response_model_by_alias=True)
    def create_plan(req: PlanRequest):
        if req.contract_version.split(".")[0] != CONTRACT_VERSION.split(".")[0]:
            raise HTTPException(
                status_code=422,
                detail=f"contract version {req.contract_version} not supported; engine speaks {CONTRACT_VERSION}",
            )
        if not req.items:
            raise HTTPException(status_code=422, detail="items must not be empty")
        bootstrap.ensure()
        with store.connect() as con:
            return plan(req, con)

    @app.get("/v1/demo/extract")
    def demo_extract():
        """Reference and inventory files of the synthetic extract, for the API's demo seeding (not sales history)."""
        bootstrap.ensure()
        directory = bootstrap.directory if bootstrap.enabled else Path(synthetic_dir) if synthetic_dir else None
        if directory is None or not (directory / "manifest.json").exists():
            raise HTTPException(status_code=404, detail="no synthetic extract configured (ENGINE_SYNTHETIC_DIR)")
        manifest = json.loads((directory / "manifest.json").read_text())
        return {
            "asOfDate": manifest["asOfDate"],
            "synthetic": True,
            "files": {name: (directory / name).read_text() for name in REFERENCE_FILES},
        }

    @app.exception_handler(FileNotFoundError)
    async def missing_store(_request: Request, exc: FileNotFoundError):
        return JSONResponse(status_code=503, content={"detail": f"analytics store not available: {exc}"})

    return app
